name: Make PDF

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: get changed files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }}| xargs)"             
      - name: echo the changed files
        run: |
          for i in ${{ steps.getfile.outputs.files }}
          do
              echo $i
          done
      - name: convert md to pdf
        run: |
          docker run -v $(pwd):/data -w /data pandoc/latex:2.9 sh -c 'for i in ${{ steps.getfile.outputs.files }}; do pandoc -d ${i:r}.yml -o ${i:r}.pdf; done'
