name: Make PDF

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-20.04
    container:
      image: docker://pandoc/latex:2.10.1
      options: --entrypoint=sh
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: |
          tlmgr update --self
          tlmgr install koma-script geometry fira lastpage fancyhdr titlesec tocloft hyperref

      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Prepare output directories
        run: |
          for d in */; do
            mkdir -p output/$d
          done

      - name: Produce pdfs
        run: |
          find . -iname '*.yml' -type f -maxdepth 1 -exec sh -c 'pandoc -d ${0} -o output/${0%.yml}.pdf' {} \;

      - name: Upload PDF Artifacts
        uses: actions/upload-artifact@master
        with:
          name: output
          path: output

      - name: Commit PDF Artifacts
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add *.pdf
          git commit *.pdf -m 'Commit PDF file(s)' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
