name: Set List

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-20.04
    container:
      image: docker://pandoc/latex:2.9
      options: --entrypoint=sh
    steps:
      - name: checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: get list of files
        id: getfile
        run: |
          echo "ls *.xml"
      - name: get list of (changed) files
        id: getfile
        run: |
          echo "::set-output name=files::$(find . -iname '*.yml' -maxdepth 1 -type f -exec sh -c 'pandoc -d ${0} -o ${0%.yml}.pdf' {} \;)"
