name: Set List

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-20.04
    container:
      image: docker://pandoc/latex:2.9
      options: --entrypoint=sh
    steps:
      - name: checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: get list of files
        run: |
          ls *.xml
      - name: produce pdfs
        run: |
          find ./ -iname '*.xml' -type f -exec sh -c 'pandoc -d ${0} -o output/${0%.yml}.pdf' {} \;
