name: Set List

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-20.04
    container:
      image: docker://pandoc/latex:2.10.1
      options: --entrypoint=sh
    steps:
      - run: |
          apt-get install texlive-latex-recommended
      - name: checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: prepare output directories
        run: |
          for d in */; do
            mkdir -p output/$d
          done
      - name: produce pdfs
        run: |
          find . -iname '*.yml' -type f -maxdepth 1 -exec sh -c 'pandoc -d ${0} -o output/${0%.yml}.pdf' {} \;
      - name: upload PDFs
        uses: actions/upload-artifact@master
        with:
          name: output
          path: output
