name: Make Set List PDF with Pandoc

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-20.04
    container:
      image: docker://pandoc/latex:2.9
      options: --entrypoint=sh
    steps:
      - name: checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: get list of (changed) files
        id: getfile
        run: |
          echo "::set-output name=files::$(find . -iname '*.yml' -type f | xargs)"
      - name: echo the changed files
        run: |
          for i in ${{ steps.getfile.outputs.files }}
          do
              echo $i
          done
      - name: convert yml to pdf
        run: |
          for i in ${{ steps.getfile.outputs.files }}
          do
              pandoc -d ${i:r}.yml -o ${i:r}.pdf
          done
